// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/entities/chat_entity.dart';
import 'data/entities/rating_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2620992702104245020),
      name: 'ChatEntity',
      lastPropertyId: const obx_int.IdUid(7, 4346105652626259248),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7168823626345510443),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4863890609776543170),
            name: 'chatId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 7833960886217313730)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3109424375274105055),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7044240463681678279),
            name: 'modelName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5499881027168933445),
            name: 'createdAt',
            type: 12,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6475045447486182352),
            name: 'updatedAt',
            type: 12,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4346105652626259248),
            name: 'messagesJson',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 930152354224104578),
      name: 'ChatStateEntity',
      lastPropertyId: const obx_int.IdUid(2, 2037545947080077728),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4305268310587395401),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2037545947080077728),
            name: 'currentChatId',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 1224459466577265631),
      name: 'RatingEntity',
      lastPropertyId: const obx_int.IdUid(5, 553142596752699985),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5791139195572041865),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5580827946614379911),
            name: 'score',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5680249508936305382),
            name: 'comment',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2230755663432000876),
            name: 'rater',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 553142596752699985),
            name: 'date',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 1224459466577265631),
      lastIndexId: const obx_int.IdUid(1, 7833960886217313730),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ChatEntity: obx_int.EntityDefinition<ChatEntity>(
        model: _entities[0],
        toOneRelations: (ChatEntity object) => [],
        toManyRelations: (ChatEntity object) => {},
        getId: (ChatEntity object) => object.id,
        setId: (ChatEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ChatEntity object, fb.Builder fbb) {
          final chatIdOffset = fbb.writeString(object.chatId);
          final titleOffset = fbb.writeString(object.title);
          final modelNameOffset = object.modelName == null
              ? null
              : fbb.writeString(object.modelName!);
          final messagesJsonOffset = fbb.writeString(object.messagesJson);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, chatIdOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addOffset(3, modelNameOffset);
          fbb.addInt64(4, object.createdAt.microsecondsSinceEpoch * 1000);
          fbb.addInt64(5, object.updatedAt.microsecondsSinceEpoch * 1000);
          fbb.addOffset(6, messagesJsonOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final chatIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final modelNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
              (const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0) /
                      1000)
                  .round());
          final updatedAtParam = DateTime.fromMicrosecondsSinceEpoch(
              (const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0) /
                      1000)
                  .round());
          final messagesJsonParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, '');
          final object = ChatEntity(
              id: idParam,
              chatId: chatIdParam,
              title: titleParam,
              modelName: modelNameParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam,
              messagesJson: messagesJsonParam);

          return object;
        }),
    ChatStateEntity: obx_int.EntityDefinition<ChatStateEntity>(
        model: _entities[1],
        toOneRelations: (ChatStateEntity object) => [],
        toManyRelations: (ChatStateEntity object) => {},
        getId: (ChatStateEntity object) => object.id,
        setId: (ChatStateEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ChatStateEntity object, fb.Builder fbb) {
          final currentChatIdOffset = object.currentChatId == null
              ? null
              : fbb.writeString(object.currentChatId!);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, currentChatIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final currentChatIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6);
          final object =
              ChatStateEntity(id: idParam, currentChatId: currentChatIdParam);

          return object;
        }),
    RatingEntity: obx_int.EntityDefinition<RatingEntity>(
        model: _entities[2],
        toOneRelations: (RatingEntity object) => [],
        toManyRelations: (RatingEntity object) => {},
        getId: (RatingEntity object) => object.id,
        setId: (RatingEntity object, int id) {
          object.id = id;
        },
        objectToFB: (RatingEntity object, fb.Builder fbb) {
          final commentOffset = fbb.writeString(object.comment);
          final raterOffset = fbb.writeString(object.rater);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.score);
          fbb.addOffset(2, commentOffset);
          fbb.addOffset(3, raterOffset);
          fbb.addInt64(4, object.date.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final scoreParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final commentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final raterParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final object = RatingEntity(
              score: scoreParam, comment: commentParam, rater: raterParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..date = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChatEntity] entity fields to define ObjectBox queries.
class ChatEntity_ {
  /// See [ChatEntity.id].
  static final id =
      obx.QueryIntegerProperty<ChatEntity>(_entities[0].properties[0]);

  /// See [ChatEntity.chatId].
  static final chatId =
      obx.QueryStringProperty<ChatEntity>(_entities[0].properties[1]);

  /// See [ChatEntity.title].
  static final title =
      obx.QueryStringProperty<ChatEntity>(_entities[0].properties[2]);

  /// See [ChatEntity.modelName].
  static final modelName =
      obx.QueryStringProperty<ChatEntity>(_entities[0].properties[3]);

  /// See [ChatEntity.createdAt].
  static final createdAt =
      obx.QueryDateNanoProperty<ChatEntity>(_entities[0].properties[4]);

  /// See [ChatEntity.updatedAt].
  static final updatedAt =
      obx.QueryDateNanoProperty<ChatEntity>(_entities[0].properties[5]);

  /// See [ChatEntity.messagesJson].
  static final messagesJson =
      obx.QueryStringProperty<ChatEntity>(_entities[0].properties[6]);
}

/// [ChatStateEntity] entity fields to define ObjectBox queries.
class ChatStateEntity_ {
  /// See [ChatStateEntity.id].
  static final id =
      obx.QueryIntegerProperty<ChatStateEntity>(_entities[1].properties[0]);

  /// See [ChatStateEntity.currentChatId].
  static final currentChatId =
      obx.QueryStringProperty<ChatStateEntity>(_entities[1].properties[1]);
}

/// [RatingEntity] entity fields to define ObjectBox queries.
class RatingEntity_ {
  /// See [RatingEntity.id].
  static final id =
      obx.QueryIntegerProperty<RatingEntity>(_entities[2].properties[0]);

  /// See [RatingEntity.score].
  static final score =
      obx.QueryDoubleProperty<RatingEntity>(_entities[2].properties[1]);

  /// See [RatingEntity.comment].
  static final comment =
      obx.QueryStringProperty<RatingEntity>(_entities[2].properties[2]);

  /// See [RatingEntity.rater].
  static final rater =
      obx.QueryStringProperty<RatingEntity>(_entities[2].properties[3]);

  /// See [RatingEntity.date].
  static final date =
      obx.QueryDateProperty<RatingEntity>(_entities[2].properties[4]);
}
